[package]
name = "sieve-of-eratosthenes-rs"
version = "0.1.0"
authors = ["Simon <simonwoodburyforget@gmail.com>"]
edition = "2018"
license = "MPL"

[dependencies]
criterion = "0.3"

[[bench]]
name = "main"
harness = false